### ISSUE TITLE
Issue with regular expression for some numeric account id's

### ISSUE THREAD

**Issue by larssb** [jonnyczi/docker-burst-plotter#1]
Hi @jonnyczi,

I had an issue with getting the docker-burst-plotter container to pick up my plot specification txt file. As I troubleshooted this I found that the regular expression in the plot bash script matches on exactly 18 chars. I don't know why but my id is above that. So I cloned the repo and fixed the "issue" in the plot file.

So....based on the above, allow me to suggest that the sub-expression that matches on what is the numeric account id is more generic and not hard-on 18 chars.

Thank you for your work and I hope you can use the above. If you have any questions feel free to respond.

**Comment by jonnyczi** [comment]
Thanks for pointing out this oversight on my part. @vangorrahas actually created a pull request for this and I have accepted it.

**Comment by larssb** [comment]
Cool. Thanks.
